exclude_patterns = [
    ".ddev",
]

[[source]]
name = "php-imap"
repository = "https://github.com/evoWeb/php-imap.git"
branch = "develop"

[[plugin]]
name = "php-codesniffer"
config_files = [ "Build/phpcs/phpcs.xml" ]
