config_version = "0"

exclude_patterns = [
    "**/.ddev/**",
    "**/.github/**",
    "**/examples/**",
]

test_patterns = [
    "**/tests/**",
]

[smells]
mode = "comment"

[smells.function_parameters]
threshold = 18

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "php-codesniffer"

[[plugin]]
name = "phpstan"
extra_packages = ["phpstan/phpstan@^2.1.43", "phpstan/phpstan-phpunit@^2.0", "paragonie/hidden-string@^2.0"]

[[plugin]]
name = "radarlint-php"
mode = "comment"

[[plugin]]
name = "ripgrep"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "zizmor"
