[[source]]
name = "php-imap"
repository = "https://github.com/evoWeb/php-imap.git"
branch = "develop"

exclude_patterns = [
    ".ddev",
]

[[plugin]]
name = "phpcs"
config_file = "Build/phpcs/phpcs.xml"
