name: PHP Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [ review_requested ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpunit:
    name: PHP ${{ matrix.php-versions }} Unit Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-versions: [ '8.2', '8.3', '8.4', '8.5' ]

    services:
      imap:
        image: dovecot/dovecot@sha256:5248022fdc8519be311e9c813dbf469e5c415fbe004015c5770a5301f03a2885
        env:
          USER_PASSWORD: testpass
        ports:
          - 31993:31993
        options: >-
          --health-cmd "nc -z localhost 31993"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: imap

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            **/.php_cs.cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: composer run phpunit
        env:
          PHPIMAP_IMAP_PATH: "{localhost:31993/imap/ssl/novalidate-cert}INBOX"
          PHPIMAP_LOGIN: testuser
          PHPIMAP_PASSWORD: testpass
